author: Luna Team
bug-reports: https://github.com/wdanilo/luna-core/issues
category: Data
copyright: Copyright (C) 2018 Luna Team

extra-source-files:
- libs/cpp-containers/cbits/*
- libs/memory-manager/cbits/*

ghc-options: [-Wall, -O2]
homepage: https://github.com/wdanilo/luna-core
library:
  source-dirs:
    - src
    - libs/cpp-containers
    - libs/foreign-utils
    - libs/mutable-list
    - libs/autovector
    - libs/memory-manager
    - libs/memory-pool
    - libs/data-tag
    - libs/typelevel
    - libs/data-mutable
    - libs/data-typemap
    - libs/th-builder
    - libs/tuple-utils
    - libs/exception
    - libs/type-cache
  c-sources:
    - libs/cpp-containers/cbits/*.cpp
    - libs/memory-manager/cbits/*.cpp
  include-dirs:
    - libs/cpp-containers/cbits
    - libs/memory-manager/cbits
  extra-libraries: stdc++
  cc-options: -std=c++17 -O2
  dependencies:
      - async
      - base
      - convert
      - containers
      - data-default
      - deepseq
      - functor-utils
      - layered-state
      - lens
      - lens-utils
      - monad-branch
      - monoid
      - mtl
      - primitive
      - prologue >= 3.0.0
      - random
      - template-haskell
      - transformers
      - vector

license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: luna-core
stability: experimental
synopsis: Luna Core
version: 0.0.1



executables:
  luna-core:
    main:         Main.hs
    source-dirs:  app
    ghc-options:  -with-rtsopts=-T
    dependencies:
      - base
      - luna-core
      - prologue
      - ekg

benchmarks:
  array-benchmark:
    main:        Test/Bench.hs
    source-dirs: test
    ghc-options: -main-is Test.Bench
    dependencies:
      - base
      - criterion >= 1.3.0.0
      - luna-core
      - vector
      - ghc
      - convert
      - deepseq
      - prologue
      - unboxed-ref >= 0.4.0.0

default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - MonadComprehensions
    - MultiWayIf
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - PackageImports
    - QuasiQuotes
    - PatternSynonyms
    - RankNTypes
    - RecursiveDo
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - UnicodeSyntax
    - ViewPatterns
    - LiberalTypeSynonyms
    - RelaxedPolyRec
