author: Wojciech Danilo
bug-reports: https://github.com/wdanilo/luna-core/issues
category: Data
copyright: Copyright (C) 2015 Wojciech Danilo

ghc-options: [-Wall, -O2]
homepage: https://github.com/wdanilo/luna-core
library:
  source-dirs:
    - src
    - libs/foreign-utils
    - libs/mutable-list
    - libs/autovector
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: luna-core
stability: experimental
synopsis: A set of benchmarks for the underlying Luna representation.
version: 0.0.1

dependencies:
    - array
    - base
    - convert
    - c-storable-deriving
    - deepseq
    - functor-utils
    - lens-utils
    - monoid
    - primitive
    - vector
    - vector-th-unbox
    - template-haskell
    - prologue >= 3.0.0

benchmarks:
  array-benchmark:
    main:        Main.hs
    source-dirs: test/bench
    dependencies:
      - criterion >= 1.3.0.0
      - luna-core
      - vector
      - ghc
      - convert

default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - Arrows
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - MonadComprehensions
#    - MonadFailDesugaring
    - MultiWayIf
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - PackageImports
    - QuasiQuotes
    - RankNTypes
    - RecursiveDo
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - ViewPatterns

    - LiberalTypeSynonyms
    - RelaxedPolyRec
