name:        luna-core
version:     0.0.2
synopsis:    Luna Core
category:    Data
license:     Apache-2.0
stability:   experimental
homepage:    https://github.com/luna/luna-core
bug-reports: https://github.com/luna/luna-core/issues
author:      Luna Team
copyright:   Copyright (C) 2018 Luna Team
maintainer:
  - Wojciech Danilo <wojciech.danilo@luna-lang.org>
  - Piotr Moczurad  <piotr.moczurad@luna-lang.org>

ghc-options:
  - -Wall
  - -O2
extra-source-files: 
  - libs/cpp-containers/cbits/*
  - libs/memory-manager/cbits/*

library:
  source-dirs:
    - src
    - libs/cpp-containers
    - libs/foreign-utils
    - libs/autovector
    - libs/memory-manager
    - libs/memory-pool
    - libs/data-tag
    - libs/typelevel
    - libs/data-typemap
    - libs/th-builder
    - libs/tuple-utils
    - libs/exception
    - libs/type-cache
  c-sources:
    - libs/cpp-containers/cbits/*.cpp
    - libs/memory-manager/cbits/*.cpp
  include-dirs:
    - libs/cpp-containers/cbits
    - libs/memory-manager/cbits
  extra-libraries: stdc++
  cc-options:      -std=c++17 -O3
  dependencies:
    - async
    - base
    - convert
    - container
    - containers
    - data-default
    - deepseq
    - functor-utils
    - layered-state
    - lens
    - lens-utils
    - monad-branch
    - monoid
    - mtl
    - primitive
    - prologue >= 3.0.0
    - random
    - template-haskell
    - transformers
    - vector

executables:
  luna-core:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
    dependencies:
      - base
      - luna-core
      - prologue

benchmarks:
  array-benchmark:
    main: Main.hs
    source-dirs: 
      - test/bench
      - test/common
    c-sources:
      - test/bench/cbits/*.cpp
    include-dirs:
      - test/bench/cbits
    extra-libraries: stdc++
    cc-options:      -std=c++17 -O3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
    dependencies:
      - ansi-terminal
      - base
      - convert
      - criterion >= 1.3.0.0
      - deepseq
      - ghc
      - layered-state
      - luna-core
      - prologue
      - unboxed-ref >= 0.4.0.0
      - vector 

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test/spec
      - test/common
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -with-rtsopts=-T
    dependencies:
      - base
      - container
      - hspec
      - hspec-expectations-lifted
      - luna-core
      - prologue
            
default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - MonadComprehensions
    - MultiWayIf
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - PackageImports
    - QuasiQuotes
    - PatternSynonyms
    - RankNTypes
    - RecursiveDo
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - UnicodeSyntax
    - ViewPatterns
    - LiberalTypeSynonyms
    - RelaxedPolyRec
