resolver: ./build/snapshot.yaml

package-indices:
    - name:            standard-hackage
      download-prefix: https://hackage.haskell.org/package/
      http:            https://hackage.haskell.org/01-index.tar.gz
      
ghc-options:
    $locals:
        -fexcess-precision
        -fexpose-all-unfoldings
        -flate-dmd-anal
        -fmax-worker-args=200
        -fspec-constr-keen
        -fspecialise-aggressively
        -fstatic-argument-transformation
        -funbox-strict-fields
        -O2
        -threaded
        -Wall
        -Wno-name-shadowing        
    $everything:
        -fconstraint-solver-iterations=100

local-bin-path: dist/bin/public/luna

packages:
    - core
    - syntax/text/lexer
    - syntax/text/model
    - syntax/text/parser
    - syntax/text/prettyprint
    
    - lib/autovector
    - lib/code-builder
    - lib/cpp-containers
    - lib/data-tag
    - lib/data-typemap
    - lib/exception
    - lib/foreign-utils
    - lib/memory-manager
    - lib/memory-pool
    - lib/nested-containers
    - lib/syntax-definition
    - lib/text-processing
    - lib/th-builder
    - lib/tuple-utils
    - lib/type-cache
    - lib/typelevel


