name       : luna-syntax-text-lexer
version    : "0.2"
author     : Luna Team <contact@luna-lang.org>
maintainer : Luna Team <contact@luna-lang.org>

library:
    source-dirs:
        - src
        - src-libs/attoparsec-text32
        - src-libs/conduit-utils
        - src-libs/parsing
    other-modules: Paths_luna_syntax_text_lexer

benchmarks:
    lexer-benchmark:
        main: Main.hs
        source-dirs: test/bench
        dependencies:
            - attoparsec
            - conduit
            - conduit-combinators
            - conduit-extra
            - criterion
            - luna-syntax-text-lexer
            - random
            - timeit


dependencies:
    - attoparsec
    - base
    - bytestring
    - conduit
    - conduit-combinators
    - container
    - containers
    - convert
    - fingertree
    - functor-utils
    - layered-state
    - lens
    - luna-core
    - luna-syntax-text-model
    - luna-parser-utils
    - luna-text-processing
    - mtl
    - prologue
    - resourcet
    - text
    - vector
    - vector-text

    # remove:
    - constraints
    - data-default
    - exceptions
    - lens-utils
    - primitive
    - transformers
    - typelevel

default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - LiberalTypeSynonyms
    - MonadComprehensions
    - MultiWayIf
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - PackageImports
    - PatternSynonyms
    - QuasiQuotes
    - RankNTypes
    - RecursiveDo
    - RelaxedPolyRec
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - UnicodeSyntax
    - ViewPatterns
    - Strict

