name: luna-core
version: 0.0.5
synopsis: Luna Core
category: Data
license: Apache-2.0
stability: experimental
homepage: https://github.com/luna/luna-core
bug-reports: https://github.com/luna/luna-core/issues
author: Luna Team
copyright: Copyright (C) 2018 Luna Team
maintainer:
- Wojciech Danilo <wojciech.danilo@luna-lang.org>
- Piotr Moczurad  <piotr.moczurad@luna-lang.org>

ghc-options:
- -Wall
- -O2

library:
  source-dirs:
  - src
  dependencies:
  - async
  - base
  - convert
  - container
  - containers
  - data-default
  - deepseq
  - functor-utils
  - ghc
  - layered-state
  - lens
  - lens-utils
  - luna-local-libs
  - monad-branch
  - monoid
  - mtl
  - primitive
  - prologue >= 3.0.0
  - random
  - split
  - template-haskell
  - transformers
  - vector

benchmarks:
  array-benchmark:
    main: Main.hs
    source-dirs:
    - test/bench
    - test/common
    c-sources:
    - test/bench/cbits/*.cpp
    include-dirs:
    - test/bench/cbits
    extra-libraries: stdc++
    cc-options: -std=c++17 -O3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - ansi-terminal
    - base
    - convert
    - criterion >= 1.3.0.0
    - deepseq
    - ghc
    - layered-state
    - luna-core
    - luna-local-libs
    - prologue
    - unboxed-ref >= 0.4.0.0
    - vector

tests:
  spec:
    main: Main.hs
    source-dirs:
    - test/spec
    - test/common
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - base
    - container
    - hspec
    - hspec-expectations-lifted
    - luna-core
    - luna-local-libs
    - prologue

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MonadComprehensions
- MultiWayIf
- NamedWildCards
- NegativeLiterals
- NoImplicitPrelude
- NumDecimals
- OverloadedLabels
- PackageImports
- QuasiQuotes
- PatternSynonyms
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UnicodeSyntax
- ViewPatterns
- LiberalTypeSynonyms
- RelaxedPolyRec
