name:       luna-resolver
version:    "0.1"
author:     Luna Team <contact@luna-lang.org>
maintainer: Luna Team <contact@luna-lang.org>

library:
    source-dirs:
        - src

tests:
    spec:
        main: Main.hs
        source-dirs: test/spec
        dependencies:
            - directory
            - filepath
            - hspec
            - hspec-jenkins
            - hspec-megaparsec
            - luna-resolver
            - luna-ci
            - luna-core
            - open-browser

dependencies:
    - base
    - containers
    - impossible
    - lens
    - luna-core
    - megaparsec
    - mtl
    - prologue
    - sbv
    - text
    - typelevel

default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - Arrows
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - LiberalTypeSynonyms
    - MonadComprehensions
    - MultiWayIf
    - NamedWildCards
    - NamedFieldPuns
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - OverloadedStrings
    - PackageImports
    - QuasiQuotes
    - RankNTypes
    - RecursiveDo
    - RelaxedPolyRec
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - ViewPatterns
#    - MonadFailDesugaring

