resolver: nightly-2018-05-05
name: luna
packages:
- hspec-expectations-lifted-0.10.0
- megaparsec-6.5.0
- placeholders-0.1

- container-0.3.3
- convert-1.4.2
- functor-utils-1.17.1
- impossible-1.1.2
- layered-state-1.1.2
- layouting-1.1.2
- lens-utils-1.4.5
- monad-branch-1.0.3
- monoid-0.1.8
- prologue-3.2.2
- terminal-text-1.1.1
- typelevel-1.2.2
- vector-text-1.1.3