resolver: lts-11.4

name: luna

packages:
    - c-storable-deriving-0.1.3
    - container-0.3.3
    - convert-1.4.2
    - criterion-1.3.0.0
    - either-5
    - functor-utils-1.17.1
    - hspec-2.5.0
    - hspec-core-2.5.0
    - hspec-discover-2.5.0
    - impossible-1.1.1
    - layered-state-1.1.2
    - layouting-1.1.2
    - lens-utils-1.4.2
    - megaparsec-6.5.0
    - monad-branch-1.0.3
    - monad-st-0.2.4.1
    - monoid-0.1.8
    - placeholders-0.1
    - prologue-3.1.6
    - terminal-text-1.1.1
    - typelevel-1.2.2
    - vector-text-1.1.2
