resolver: lts-11.4

name: luna

packages:
- layered-state-1.1.2
- impossible-1.1.2
- typelevel-1.2.2
- container-0.3.3
- hspec-core-2.5.0
- layouting-1.1.2
- monoid-0.1.8
- hspec-discover-2.5.0
- criterion-1.3.0.0
- terminal-text-1.1.1
- placeholders-0.1
- monad-st-0.2.4.1
- c-storable-deriving-0.1.3
- lens-utils-1.4.5
- megaparsec-6.5.0
- convert-1.4.2
- hspec-2.5.0
- vector-text-1.1.3
- either-5
- monad-branch-1.0.3
- prologue-3.2.2
- functor-utils-1.17.1
