resolver: nightly-2018-05-05
name: luna
packages:
- megaparsec-6.5.0
- layered-state-1.1.3
- convert-1.5
- typelevel-1.2.2
- container-1.1.0
- layouting-1.1.3
- monoid-0.1.8
- vector-text-1.1.3
- lens-utils-1.4.5
- hspec-expectations-lifted-0.10.0
- monad-branch-1.0.3
- prologue-3.2.3
- functor-utils-1.17.1
- impossible-1.1.2
- placeholders-0.1
- terminal-text-1.1.1
