resolver: lts-11.4
name: luna-local
packages:
- c-storable-deriving-0.1.3
- criterion-1.3.0.0
- either-5
- hspec-2.5.0
- hspec-core-2.5.0
- hspec-discover-2.5.0
- megaparsec-6.5.0
- monad-st-0.2.4.1
- placeholders-0.1

