name:       luna-syntax-text-parser
version:    "0.2"
author:     Luna Team <contact@luna-lang.org>
maintainer: Luna Team <contact@luna-lang.org>

library:
    source-dirs:
        - src
        - src-libs

tests:
    spec:
        main: Main.hs
        source-dirs: test/spec
        dependencies:
            - luna-core
            - luna-syntax-text-parser
            - luna-syntax-text-prettyprint
            - luna-syntax-text-lexer
            - directory
            - filepath
            - hspec
            - hspec-megaparsec == 0.3.1
            - hspec-expectations-lifted
            - open-browser
            - container


dependencies:
    - base
    - luna-core
    - luna-syntax-text-lexer
    - luna-syntax-text-model
    - prologue
    - layered-state
    - lens
    - lens-utils
    - megaparsec == 5.3.1
    - containers
    - mtl
    - text
    - typelevel
    - vector
    - vector-text
    - layouting
    - luna-text-processing
    - luna-foreign-utils
    - luna-syntax-definition

default-extensions:
    - AllowAmbiguousTypes
    - ApplicativeDo
    - Arrows
    - BangPatterns
    - BinaryLiterals
    - ConstraintKinds
    - DataKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveFoldable
    - DeriveFunctor
    - DeriveGeneric
    - DeriveTraversable
    - DoAndIfThenElse
    - DuplicateRecordFields
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - FunctionalDependencies
    - GeneralizedNewtypeDeriving
    - InstanceSigs
    - LambdaCase
    - MonadComprehensions
#    - MonadFailDesugaring
    - MultiWayIf
    - NamedWildCards
    - NegativeLiterals
    - NoImplicitPrelude
    - NumDecimals
    - OverloadedLabels
    - PackageImports
    - QuasiQuotes
    - RankNTypes
    - RecursiveDo
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeFamilyDependencies
    - TypeOperators
    - ViewPatterns

    - LiberalTypeSynonyms
    - RelaxedPolyRec
    - UnicodeSyntax
